# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='best_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.Person'),
        ),
    ]
